### ISSUE TITLE
Importing list of following channels doesn't work anymore

### ISSUE THREAD

**Issue by Violetnred2** [joaopsys/NowStreaming-Firefox#3]
Options > Your Twitch Name > Add/Replace
Neither adding nor replacing the list of followed channel changes the extension's stored list. But opening a channel page and clicking Follow/Unfollow in the extension does work.

**Comment by Violetnred2** [comment]
Nevermind!
Options > Disconnect From Twitch, then reconnect back again. That fixes the issue.

**Comment by joaopsys** [comment]
Glad you got it fixed! This was actually due to a change on Twitch's side and a reconnect is needed from NowStreaming 3.4 and above.


https://addons.mozilla.org/en-US/firefox/addon/nowstreaming-twitch/

3.4:
- Fix/Update the "Import From Twitch" button: Due to Twitch's new API limitations, from now on this function will only be able to read and import your own user's followed channels. It will not be possible to import the list of other user's followed channels. For 99% of users, this will not be a significant change.
- Update Twitch OAuth permissions accordingly
- You will need to disconnect from twitch (in the Options menu) and re-authenticate for these changes to take effect
